version: '3.9'
services:
    equake:
      user: ${UID}:${GID}
      build: .
      volumes:
        - .:/app
        -  /run/user/${UID}/bus:/run/user/${UID}/bus
      environment:
        - DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}
      security_opt:
        - seccomp:unconfined
      privileged: true